name: 'Add Annotations from JUnit Test Report Failures'
description: 'Parses JUnit'
author: "Qapital"
inputs:
  test_result_path:
    description: 'Location of the test report file. File location is relative to GITHUB_WORKSPACE.'
    required: true
  token:
    description: 'The authentication token to use when posting check annotations.'
    required: true
  commit_sha:
    description: 'The commit SHA that this check is running on.'
    required: true
  check_name:
    description: 'The name of the check'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
